source/Tools.MetaDataProcessor/Various.cpp
- Add new parameters and code to support new properties: Platform and TargetName.
=> Update declaration of NFReleaseInfo::Init

source/version.json
=> Update nf-interpreter sub-module @73389fa

source/Tools.MetaDataProcessor/Info_Win32.cpp, source/version.json
=> Fix header file name in include stub

source/MetadataProcessor.Console/Options.cs, source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/Tables/nanoFieldDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Implement excludeClassByName option

source/MetadataProcessor.Console/Options.cs, source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Skeleton code only. No real implementation.
=> Add minimize option

source/MetadataProcessor.Console/Options.cs, source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Add verbose option

source/MetadataProcessor.Core/Tables/nanoFieldReferenceTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodReferenceTable.cs, source/MetadataProcessor.Core/Tables/nanoReferenceTableBase.cs, source/MetadataProcessor.Core/Tables/nanoResourceFileTable.cs, source/MetadataProcessor.Core/Utility/nanoBitmapProcessor.cs, source/MetadataProcessor.Core/Utility/nanoDependencyGeneratorWriter.cs, source/MetadataProcessor.Core/Utility/nanoFontProcessor.cs, source/MetadataProcessor.Core/Utility/nanoPdbxFileWriter.cs
=> Fix framework naming throughout the code files

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
- Wasn't returning properly formated type.
=> Fix GetnanoClrTypeName

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
- Conditions to include class in stubs wheren't enterily correct.
=> Fix IncludeInStub

source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
=> Fix assembly header template

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Include in stubs wasn't excluding constant fields.
- Extendend classes wasn't counting correctly the fields offset.
=> Fix GenerateAssemblyHeader

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Fix static fields count in skeleton generator

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Was wrongly using HasConstant instead of IsLiteral.
=> Fix condition to process fields

source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/Utility/nanoTypeDefinitionFlags.cs
- Fix bug with TypeSpecification check (WIP).
- Fix condition to search existing signature in table.
- Remove and comment ignore attributes collection (WIP).
- Rename vars for consistency.
- Correct var name typos.
- Tidy constants to improve readability.
=> Several fixes and rework

source/MetadataProcessor.Console/MetadataProcessor.Console.csproj, source/MetadataProcessor.Console/app.config, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoReferenceTableBase.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs, source/MetadataProcessor.Core/Utility/nanoPdbxFileWriter.cs, source/MetadataProcessor.Core/app.config, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Improvements in assembly minimization algorithm

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Update version output on console test app.
=> Add step to renormalize tables when minimizing an assembly

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/Tables/nanoAttributesTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Correct processing of MemberRef, Field and Field with CustomAttributes.
- Add missing processing to remove unused attributes.
- Fix processing argument of console test app.
=> Fixes on minimize assembly

source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoReferenceTableBase.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Fix wrong fields counter when the class has no fields.
- Fix code to deal with null attributes
- Add IsCoreLib to assembly builder.
- Custom attributes has to use type full name.
- Remove unused code.
- Add code to update backing field on remove unused items.
- Add processing to make sure we have the required type definition order.
=> Fix type processing

source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
=> Fix signature output for type definitions

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize for method ref

source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix signature generation

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Also minor fix in output message.
=> Add missing type ref processing on method body

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Improve output of verbose minimize.
=> Fix minimize of FieldDefs

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix in minimize processing Member refs and fields

source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Improvements in minimize stage when cleaning the string table

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Addresses nanoframework/Home#569.
=> Fix minimize processing for enum parameters

source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs, source/version.json
- Rework pre allocation from used strings.
- Fix output of user strings in dump generator.
- Bump version to 2.19.0
=> Rework string table minimization

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Add check for missing AssemblyNativeVersionAttribute

source/MetadataProcessor.Console/MetadataProcessor.Console.csproj, source/MetadataProcessor.Console/app.config, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/version.json
=> Update target famework to 4.7.2

source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
=> CRC32 for native methods is now always updated

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Addresses nanoframework/Home#573.
=> Fix edge case in minimization step for referenced enum types

source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize step for resources

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Add GetNativeChecksum() to access native checksum

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Closes nanoframework/Home#579
=> Fix marshalling return type

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
=> Fix class name generator for skeletons

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
=> Fix output of byref array parameters

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
=> Fix processing of parameter type with arrays and nested arrays

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimization processing for array body vars

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize processing for method definition with return array type

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Wrap critical sections with try/catch to output meaningful error message.
=> Improve minimize processing

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize processing for method references with primitive types

source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Improve condition check when not finding type definition for method reference.
=> Fix minimize step for method ref returning array

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Several fixes in minimize code

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoAssemblyDefinition.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Fix wrong calculation of native methods checksum

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimization of return types with arrays

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize Method refs with type classes

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
=> Fix minimize of Method return type

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Fixes nanoFramework/home#597.
=> Fix processing of array parameter type in method minimization

source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Output was wrongly creating a new metadata token instead of using the current one.
=> Fix output of TypeRef dump

source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
- Change native type for data types I4 and U4 to native declarations.
⚠️ In the future it would advisable to review the native declarations to match the native in use ⚠️ 
- Resolves nanoFramework/Home#601.
- Tested with the sample code in the issue.
=> Fix native type for data types I4 and U4 (to match native declarations)

source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
Nothing special but wiping with some MrProper over the code..
Signed-off-by: Thomas Karl Pietrowski <thopiekar@googlemail.com> (github: thopiekar)
=> SkeletonTemplates: Removing useless whitespaces

source/MetadataProcessor.Core/DumpGenerator/AttFixedArgs.cs, source/MetadataProcessor.Core/DumpGenerator/AttributeCustom.cs, source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Fix flag for method.
- Fix dumping custom attributes.
=> Fix custom attributes processing

source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Fix processing dump output in custom attributes.
=> Fix processing dump output in custom attributes

source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
The for-loop just looks a bit better then.
Signed-off-by: Thomas Karl Pietrowski <thopiekar@googlemail.com>
=> SkeletonTemplates: Tweaking the formatting a bit

source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassTable.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Now only classes with stubs are included.
- Add new class to list classes with stubs.
- Update template accordingly.
- Fixes issue with CMake module including files for classes that didn't have stubs.
=> Fix CMake module generator

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs, source/version.json
- Add code to export enum types.
- Add code to skeleton generator to add enum declarations.
- Update assembly classes for templates.
- Bump version to 2.23.
- Automatic export of the managed enums it's the only way to be sure that thety are kept in sync between managed declaration and native. Previously this has to be a manual job relying on the developer to do it and most critical remembering to do so.
=> Managed enums are now exported to class declaration

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Enum names now include namespace and/or class they belong to disambiguate.
- Enums out of a class are now included too.
- Enum are now exported as typedef to allow using them in structs and properties.
- Enum export now honours property to exclude enum by class name.
- Improves enum export
=> Improve enum export code

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Improvements in enum export.
- Now it's possible to exclude enums just by the name (in case they don't belong to a class).
=> Improvements in enum export

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
- Add extra code to process situations where the type namespace isn't available.
- Resolves nanoFramework/Home#609
=> Fix enum exported when namespaces aren't correctly processed

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Fix dump of assembly indexes.
- Implement dump of exception handlers.
=> Fix processing of method exception handlers

source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
- Remove System.WeakReference from primitive data types.
- Fixes nanoFramework/Home#614.
=> Fix primitive datatypes

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- improve code in exception processing when there is only finally. Also on respective dumper code to handle the situation.
=> Fix exception processing when there is only finally

source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Improve handling of exceptions in typos dumper code when some exception properties are null.
=> Improve handling of exceptions in typos dumper code

source/MetadataProcessor.Core/Utility/LoadHintsAssemblyResolver.cs
- Add exception processing on Resolve to output helpful error in case the requested assembly is not on the load hints collection.
- Improves reliability and usability.
=> Add output of error on resolution failure because of missing assembly

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
- Improve code to deal with null namespaces, declaring types and other edge situations.
- General improvements on code.
- Addresses nanoframework/Home#621.
=> Improve enum to type parsing

MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Improve code to deal with Interfaces removal during minimization.
- Fix template of TypeDef dump.
- Fixes nanoFramework/Home#631.
- Test project in issue.
=> Fix wrong processing of Interfaces in minimization

MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Fix checking of return type on dependency list processor.
- Fixes nanoFramework/Home#641.
=> Fix edge case with method return type byRef

MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
- Add missing process of byref params in dump typeref.
=> Add missing process of byref params in dump typeref

MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, version.json
- Update copyright header.
- Add missing path for class declaration.
=> Fix template generator for CMake

MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, MetadataProcessor.Core/nanoDumperGenerator.cs
- Was missing the definition of HasFinalizer.
=> Fix processing of typedef flags

MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Was wrongly removing entries for types on the exclusion list.
=> Fix method lookup generator

MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs, MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, version.json
- Add missing entries of primitive types.
- Bump version to 2.27.
- These entries for primitive type that have differentiated handling were missing.
- Building mscorlib in debug mode and checking the dump files.
=> Add missing entries of primitive types

MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/packages.config, version.json
- Update version config.
- Update NBGV package to 3.3.37.
=> Work CD-CI

MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, version.json
- Remove reflection types from primite type table.
- Bump version to 2.28.
=> Remove reflection types from primite type table

MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
- Fix pointer parameter in template.
=> Fix template

MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
- Fixes generating signature of generic method.
- Generic Instance loose their datatype when formerly resolved as object.
=> Preserve DataType for Generic Instance

MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
- Generic parameters should be object type.
- Rework conditions to write correct data type for generics.
- Generic parameters should be handled as object type objects.
=> Remove DATATYPE_GENERIC

MetadataProcessor.Console/MetadataProcessor.Console.csproj, MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/packages.lock.json
=> Update Mono.Cecil to 0.11.3

MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, MetadataProcessor.Core/DumpGenerator/GenericParam.cs, MetadataProcessor.Core/DumpGenerator/TypeDef.cs, MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs, MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/Tables/nanoGenericParamTable.cs, MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, MetadataProcessor.Core/Tables/nanoTablesContext.cs, MetadataProcessor.Core/nanoAssemblyBuilder.cs, MetadataProcessor.Core/nanoDumperGenerator.cs, MetadataProcessor.Core/nanoSkeletonGenerator.cs, nanoFramework.Tools.MetadataProcessor.sln, version.json
- Add new nanoReference table for GenericParam.
- Update tables context to include generic types and parameters.
- Update signatures generator to handle generic types.
- Update methods in asembly builder to handle generics.
- Fix output type to properly handle all generic typre.
- Add GenericParam class for output template.
- Update output to include generic parameters.
- Bump version to 2.30.
- Continue work to add support for generics.
=> Work on adding support for generics

MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, MetadataProcessor.Core/Utility/nanoCLR_DataType.cs, MetadataProcessor.Core/nanoAssemblyBuilder.cs, version.json
- Add new datatypes following ECMA-335.
- Rework type signature generator to handle generic arrays, instances and parameters.
- Rework method signature generator to handle generic method refs.
- Remove wrong processing in subtype writing.
- Bump version to 2.31.
- More work towards generic support.
=> Work adding support for generics

MetadataProcessor.Core/Tables/nanoFieldReferenceTable.cs, MetadataProcessor.Core/Tables/nanoMethodReferenceTable.cs, MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Add experimental processing of field and method refs to add support for generics.
- Work towards supporting generics.
=> Add processing of field ref and method ref to support generics

MetadataProcessor.MsBuildTask/MetaDataProcessorTask.cs, MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj, MetadataProcessor.MsBuildTask/Properties/AssemblyInfo.cs, MetadataProcessor.MsBuildTask/TasksConstants.cs, MetadataProcessor.MsBuildTask/Utilities/DebuggerHelper.cs, MetadataProcessor.MsBuildTask/nanoFramework.Tools.MetadataProcessor.MsBuildTask.targets, MetadataProcessor.MsBuildTask/package.nuspec, MetadataProcessor.MsBuildTask/packages.lock.json, azure-pipelines.yml, azure-pipelines/update-dependencies.ps1, nanoFramework.Tools.MetadataProcessor.sln, version.json
- Add new project to output MSBuild Task.
- Update azure build pipeline to pack new NuGet.
- Update PS1 to update VS extension dependents.
- Produce NuGet with MSBuild Task for MDP allowing direct consumption by VS extension.
- Work towards adding Unit Testing to MDP.
=> Add MSBuild task with MDP

MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
- Rework WriteDataType to handle correctly VAR data types.
- Add assert to MethodDef to validate output length written to table.
- Add new generic related flags to Method flags (WIP).
=> Fix processing of generic type

MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj, MetadataProcessor.Tests/Core/ClrIntegrationTests.cs, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, MetadataProcessor.Tests/TestNFApp/Program.cs, MetadataProcessor.Tests/TestObjectHelper.cs, azure-pipelines.yml, nanoFramework.Tools.MetadataProcessor.sln, version.json
- Add mscorlib sub-module.
- Add referenced library to tests.
- Fix CodeWrite test.
- Add unit tests for assembly refs.
- Add test class to run assemblies built with compiled MDP.
- Update TestObjectHelper to allow code reuse.
- Minor changes to program main() on test app.
=> Improvements in Unit Tests

MetadataProcessor.Core/Tables/nanoTypeSpecificationsTable.cs
- Add check for array in typespec.
- Throwing exception when that's the case.
- Resolves nanoFramework/Home#684.
=> Add check for multidimensional arrays

MetadataProcessor.MsBuildTask/package.nuspec
=> Work CI-CD

MetadataProcessor.Core/nanoAssemblyBuilder.cs, azure-pipelines.yml
- Validates unsupported pointer type variables and throws build error.
=> Add check for unsupported pointer type variables

MetadataProcessor.MsBuildTask/package.nuspec
=> Update nuspec with Cecil

MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Dependency builder was not processing correctly fields when field is array and element type is located on another assembly.
- Fixes nanoFramework/Home#752.
=> Fix processing of array field

MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj
=> Fix refs in packaging

MetadataProcessor.MsBuildTask/nanoFramework.Tools.MetadataProcessor.MsBuildTask.targets
- Remove MetadataProcessor.Core from targets.
- This DLL is not used anymore.
=> Remove MetadataProcessor.Core from targets

MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/packages.lock.json, MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, MetadataProcessor.Tests/TestNFApp/TestNFApp.nfproj, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/TestNFClassLibrary.nfproj, azure-pipelines.yml, nanoFramework.Tools.MetadataProcessor.sln
- Rework Unit Test project so it can build both locally and at the pipeline.
- Update mscorlib sub-module.
- Brought nfprojs for Unit Tests up to date.
- Update pipeline yaml to run unit tests.
- Update nuget refs.
=> Update Unit Tests

MetadataProcessor.Tests/Core/ClrIntegrationTests.cs, MetadataProcessor.Tests/Core/Endianness/nanoBinaryWriterTests.cs, MetadataProcessor.Tests/Core/Extensions/ByteArrayExtensionsTests.cs, MetadataProcessor.Tests/Core/Extensions/ParameterDefintionExtensionsTests.cs, MetadataProcessor.Tests/Core/Extensions/TypeDefinitionExtensionsTests.cs, MetadataProcessor.Tests/Core/Extensions/TypeReferenceExtensionsTests.cs, MetadataProcessor.Tests/Core/Mono.Cecil/CodeWriterTests.cs, MetadataProcessor.Tests/Core/Tables/nanoAssemblyReferenceTableTests.cs, MetadataProcessor.Tests/Core/Tables/nanoAttributesTableTests.cs, MetadataProcessor.Tests/Core/Tables/nanoReferenceTableBaseTests.cs, MetadataProcessor.Tests/Core/Utility/Crc32Tests.cs, MetadataProcessor.Tests/Core/Utility/LoadHintsAssemblyResolverTests.cs, MetadataProcessor.Tests/Core/Utility/NativeMethodsCrcTests.cs, MetadataProcessor.Tests/Core/Utility/nanoBitmapProcessorTests.cs, MetadataProcessor.Tests/Core/Utility/nanoDependencyGeneratorWriterTests.cs, MetadataProcessor.Tests/Core/Utility/nanoStringsConstantsTests.cs, MetadataProcessor.Tests/TestObjectHelper.cs
- Add missing license headers to Unit Test source files.
- Fix multiple code style issues.
- Replace several methods wit properties in TestObjectHelper.
=> Code style fixes

MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/packages.lock.json, MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj
- Upgrades packages in:
- Core
- MsBuildTask
- Tests
I ran the existing tests to see if anything had broken, nothing had.
=> Upgrade NuGet packages

MetadataProcessor.Shared/SkeletonGenerator/SkeletonTemplates.cs, MetadataProcessor.Shared/nanoSkeletonGenerator.cs, MetadataProcessor.Tests/Core/StubsGenerationTests.cs, MetadataProcessor.Tests/StubsGenerationTestNFApp/NativeMethodGeneration.cs, MetadataProcessor.Tests/StubsGenerationTestNFApp/StubsGenerationTestNFApp.nfproj, README.md
Fixes the following Issues: 
There are tests written that test the changes made
=> Stub generation fixes

MetadataProcessor.Shared/SkeletonGenerator/SkeletonTemplates.cs
- Code style fixes in class template.
- Update template for cmake stubs.
- Fixes on several templates to match code style and other minor tweaks.
=> Updates on several templates

MetadataProcessor.Shared/Tables/nanoResourcesTable.cs
- Check added resources for supported bitmaps only, jpeg,bmp,gif all other files are binary.
- Issue on building projects with ICO resources.
Added icons, various unsupported bitmaps, read these into a C# program and checked the arrays
- correct length
- correct data for the first 10 bytes
- correct data for the last 10 bytes
=> Fix processing ICO type resources

MetadataProcessor.Core/packages.lock.json, MetadataProcessor.Tests/Core/Utility/DumperTests.cs
- Microsoft.SourceLink.GitHub
- Mono.Cecil
- Nerdbank.GitVersioning
- Microsoft.Build.Tasks.Git
- Microsoft.SourceLink.Common
- Fix unit test.
- Unit test needed to be fixed following a bug fix in Mono.Cecil.
=> Update several references
