source/Tools.MetaDataProcessor/Info_Win32.cpp
- Fixes nanoframework/Home#524.
=> Fix include name

source/MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
- Add missing entries to the enum to have an exact match with C++ `enum CLR_DataType`.
=> Update nanoCLR_DataType enum

azure-pipelines.yml, source/MetadataProcessor.Console/MetadataProcessor.Console.csproj, source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassStubs.cs, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyLookupTable.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoFieldDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs, source/MetadataProcessor.Core/Utility/nanoTypeDefinitionFlags.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs, source/MetadataProcessor.Core/packages.config
- Fix generation of method name and class names to follow .NETMF rules.
- Fix native methods CRC32 calculation.
- Fix implementation of class name to exclude.
- Major rework on several helper classes to make the above work.
- Add templates for assembly header, lookup table and class stubs.
⚠️ Regular and core libs. Interop is not supported yet. ⚠️
=> Add skeleton generator

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Update interop option to match targets and definition of existing build system

azure-pipelines.yml, source/MetadataProcessor.Core/package.nuspec, source/version.json
- Console app is no longer packaged for distribution.
- Bump version to 2.1.
=> NuGet package now contains Core DLL instead of Console app

source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
- Fields were being offset because of different marker sizes.
=> Fix PE header generator

source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
- Native assembly version was being wrongly ouput.
=> Fix AssemblyLookupTemplate

source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
- Was making a wrong replacement on the namespace.
=> Fix GetMethodName

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
- Wasn't writing this field thus preventing deployment and assembly check on target boot.
=> Fix compile to output native methods CRC for core libraries

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Counter update can only happen after fields are enumerated.
=> Fix static fields counter

source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs
- Fix parsing of method flags: a couple of wrongly set flags and others not properly set.
- Fix generation of locals signature.
- Tidy up internal constants to improve code readability.
=> Rework method definition parsing

source/MetadataProcessor.Console/MetadataProcessor.Console.csproj, source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Console/app.config, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Mono.Cecil/CodeWriter.cs, source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoReferenceTableBase.cs, source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoTypeSpecificationsTable.cs, source/MetadataProcessor.Core/Utility/nanoPdbxFileWriter.cs, source/MetadataProcessor.Core/Utility/nanoStringsConstants.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDependencyGenerator.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs, source/MetadataProcessor.Core/packages.config
- Rework code to process these.
- Heavy rework to match original implementation of minimize algorithm of native MDP.
- Fix some bugs in method inclusion/exclusion.
- Fix some typos in comments.
- Update NuGet packages.
=> Add minimize and verbose parameters

source/MetadataProcessor.Core/Tables/nanoFieldDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoReferenceTableBase.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs
- Fix code that outputs the fields reference for class types.
- Add missing code to remove unused items for field definitions table.
=> Fix field definition output

source/MetadataProcessor.Core/Extensions/ByteArrayExtensions.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/native/Tools.MetaDataProcessor/WatchAssemblyBuilder.h, source/native/Tools.Parser/Linker.cpp
- Fix value for type ref flag.
- Add debug output on both managed and native versions.
=> Fix signature generator

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/DumpGenerator/AssemblyRef.cs, source/MetadataProcessor.Core/DumpGenerator/DumpAllTable.cs, source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/DumpGenerator/ExceptionHandler.cs, source/MetadataProcessor.Core/DumpGenerator/FieldDef.cs, source/MetadataProcessor.Core/DumpGenerator/ILCode.cs, source/MetadataProcessor.Core/DumpGenerator/InterfaceDef.cs, source/MetadataProcessor.Core/DumpGenerator/LocalDef.cs, source/MetadataProcessor.Core/DumpGenerator/MemberRef.cs, source/MetadataProcessor.Core/DumpGenerator/MethodDef.cs, source/MetadataProcessor.Core/DumpGenerator/TypeDef.cs, source/MetadataProcessor.Core/DumpGenerator/TypeRef.cs, source/MetadataProcessor.Core/DumpGenerator/UserString.cs, source/MetadataProcessor.Core/Endianness/nanoBinaryWriter.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Mono.Cecil/CodeWriter.cs, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/MetadataProcessor.Core/Tables/nanoStringTable.cs, source/MetadataProcessor.Core/Utility/nanoCLR_DataType.cs, source/MetadataProcessor.Core/Utility/nanoSerializationType.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Add missing native element types and data types.
- Fixes in data types parsing.
- Fixes in signature parsing.
- Fixes in minimize interfaces.
- Add templates and dump all generator.
- Correct several typos in comments.
=> Implement dump all

source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs, source/MetadataProcessor.Core/Utility/nanoCLR_DataType.cs, source/MetadataProcessor.Core/Utility/nanoSerializationType.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs, source/native/Tools.Parser/AssemblyParserDump.cpp
- Remove wrong entries in Primitives dictionary.
- Fix output of method parameters types.
- Fix output of dump CLR types.
- Add extra output to native MDP dumper (to output IL count for each method).
=> Several fixes in signature generation

source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Add several assembly attributes to exclusion list.
- Add missing code to filter type refs and type defs that are listed in exclusion list.
- Improve code with extension to filter excluded classes.
- Minor tweaks in dumper code.
=> Improvements in attributes exclusion

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeReferenceTable.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs
- Remove assembly attributes from ignore list (not required as they will be added as non used items).
- Remove minimize command. Now all assemblies are minimized by default.
- Add missing call to RemoveUnusedItems() in TypeReferencesTable.
- Improve dumping of type references entry: wasn't getting the correct scope.
=> Fix type references processing

source/MetadataProcessor.Console/Program.cs, source/MetadataProcessor.Core/Tables/nanoAssemblyReferenceTable.cs, source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoFieldDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoFieldReferenceTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs, source/MetadataProcessor.Core/Tables/nanoMethodReferenceTable.cs, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs, source/MetadataProcessor.Core/Utility/nanoPdbxFileWriter.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Byte code table is now generated only after minimize step (output was wrong because the second pass was working on the already tweaked offsets table).
- Add asserts in PDBX generator.
- Update console test app.
=> Fix issue with bye code output

source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/Tables/nanoTablesContext.cs, source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Fix bug with checking of attributes to exclude.
- Expose IgnoringAttributes collection.
- Add extension to check typered against attributes list.
- Several improvements in MemberRef and Field tokens processing.
=> Several fixes with minimization workflow

source/MetadataProcessor.Core/DumpGenerator/AttributeCustom.cs, source/MetadataProcessor.Core/DumpGenerator/DumpAllTable.cs, source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/nanoDumperGenerator.cs, source/native/Tools.Parser/AssemblyParserDump.cpp
- Add code for typeref and custom attributes.
- Update code in native implementation to match formating.
=> Improvements dump metadata generator

source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs, source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
- Fix primitive types UIntPtr and IntPtr.
=> Fixes in method signature generator

source/MetadataProcessor.Core/DumpGenerator/DumpAllTable.cs, source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs, source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/nanoDependencyGenerator.cs, source/MetadataProcessor.Core/nanoDumperGenerator.cs, source/MetadataProcessor.Core/nanoFramework.Tools.MetaDataProcessor.Core.targets, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs, source/MetadataProcessor.Core/package.nuspec, source/MetadataProcessor.Core/packages.config, source/version.json
- Stubble.Core with mustache-sharp.
- Update code accordingly.
- Update templates accordingly.
- Fix properties of DumpAll class.
- Bump version to 2.18.0.
=> Replace template generator

source/MetadataProcessor.Core/MetadataProcessor.Core.csproj, source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassTable.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
=> Add CMake generator for Interop skeleton

source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassTable.cs, source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs, source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- CMake find module is now generated for both class libs and interop libs.
- Fix naming of global assembly declaration.
- Fix naming of classes and files to have common code for all situations.
=> Improve skeleton generator

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Otherwise, we will keep using param0 for every generated parameter instead of using param{n} per loop run.
Discussed on Discord.
Signed-by: Thomas Karl Pietrowski <thopiekar@github.com> (github: thopiekar)
=> Fix parameterIndex increment in skeleton generator for Interop

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Just noticed that the name of the array's type doesn't fit to the comment above it.
Additionally, I (hopefully) fixed an issue with the type generation for regular data types.
However, I haven't tested these changes practically.
Signed-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)
=> Fix marshalling declaration using CLR types in skeleton generator

source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
- This is required to mark to other tools if the assembly required native support. Interop libraries require native support to be present on the target. With this change the NativeMethodsCheckSum position in the PE can now be used to signal this. When the value it's 0, the assembly does not hava native implementation.
- Addresses nanoframework/Home#575.
=> Add processing to update native methods CRC32

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
- Nested types weren't being properly handled. Now they are.
=> Fix issue with nested types

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Skeleton files generation is now skipped for assemblies that do not have native implementation.
- Native checksum is now output so it shows on build log.
=> Improvements in skeleton generator

source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
- Can't use `HasFlags` because of the need to reuse the C++ flags structure which is not well replicable in C#.
- Fixes nanoFramework/Home#588.
=> Fix checking for class inclusion in typedef extension

source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
- Fix code generating signature for array elements. The original code had a workaround to fix the signature length which was producing a wrong output for arrays larger than 255 elements.
- Fixes nanoFramework/Home#552.
- Fixes nanoFramework/Home#595.
- Test app in the issue above.
=> Fix signature generator for array elements

source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
nanoAttributesTable.RemoveUnusedItems() uses attribute.Constructor.MetadataToken for checks while nanoAssemblyBuilder put attribute.AttributeType.MetadataToken into dependency list.
This results in losing class attributes.
(While processing field and method attributes both components use constructor.MetadataToken)
- Fixes nanoFramework/Home#599
Debug trace.
Signed-off-by: SandorDobos <dbs.sndr@gmail.com>
=> Fix minize step for CustomAttributes in dependency collection

source/MetadataProcessor.Core/Mono.Cecil/CodeWriter.cs
- Fix calculation of TypeDef id for TypeSpec entries.
- Fixes nanoFramework/Home#592.
- Sample code in the issue. Compared with output from old MDP.
=> Fix TypeRef ID calculation for TypeSpec entry

source/MetadataProcessor.Core/Utility/LoadHintsAssemblyResolver.cs
- Assembly resolution now uses exclusively the assemblies provided by load hints, not the ones from the full .NET framework.
- Using the .NET framework assemblies (like mscorlib) was wrong and lead to potential errors by using types from assemblies other than nF ones.
=> Fix assembly resolution

source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
- Fix algorithm to find count of class fields when class is a derived one.
- The calculation was wrong when the base type was from a different assembly.
=> Fix indexing of class fields for derived classes

MetadataProcessor.Core/Tables/nanoTablesContext.cs
- Improve filtering of MemberReferences to include primitive types of arrays.
- Filter was wrongly ignoring primitive types of multidimensional arrays.
- Fixes nanoFramework/Home#629.
- Successfull compilation of application with array as mentioned in the issue.
=> Fix filtering member references

MetadataProcessor.Core/Extensions/MethodDefinitionExtensions.cs, MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs, MetadataProcessor.Core/MetadataProcessor.Core.csproj, MetadataProcessor.Core/Tables/nanoSignaturesTable.cs, MetadataProcessor.Core/Utility/NativeMethodsCrc.cs, MetadataProcessor.Core/Utility/nanoCLR_DataType.cs, MetadataProcessor.Core/nanoDumperGenerator.cs
A method of signature
```
T Do<T>();
```
was being generated as
```
void Do<T>();
```
which causes the runtime not to copy the result on the returning function stack to its caller stack, thereby corrupting the stack and crashing.
This changes allows the returned generic parameter and instance to be generated as object rather than void
This is meant to open opportunities to advance C# techniques, especially async
Using the console app to generate a PE for an assembly containing generics and loading the generated PE on nanoCLR
=> Add support to process methods with generics <T> in parameters and as return type

MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
- Add extra parsing in the code handling the type name.
- Was causing issues in enums without '.' in the namespace.
- Successfully building the test project reported in the issue.
- Fixes nanoframework/Home#703.
=> Fix building native enum from managed

MetadataProcessor.Tests/MetadataProcessor.Tests.csproj
- Remove the need to set env variable to use test MDP msbuild task.
- Improves local development experience.
=> Rework building of nfprojs for Unit Tests

MetadataProcessor.Tests/Core/ClrIntegrationTests.cs
- Fix search for exception in CLR integration test.
- Was only able to find System.Exception, missing all the others.
=> Fix search for exception in CLR integration test

README.md
=> Add a developers guide to the README

MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, README.md
- Adds `-nr=False` flags to the pre-build-event of the test project.
- Updates documentation for future contributors so they know the need for the flag.
I did a couple of rebuilds quickly after another and none of them had the issue where MsBuild could not be copied.
Note: The rebuilds are *slightly* slower
=> Adds flags to enable quick rebuilds

MetadataProcessor.Shared/Tables/nanoResourcesTable.cs, MetadataProcessor.Shared/Utility/nanoBitmapProcessor.cs, MetadataProcessor.Tests/Core/Utility/nanoBitmapProcessorTests.cs
Bitmap as embedded resources were not working.
Note:
Mono.Cecil reader returns resources as strings, and System.Byte[ ].
System.Drawing.Bitmap is read by Mono.Cecil as a System.Byte[ ].
A try to convert the System.Byte[ ] is the only way to detect bitmaps.
Embedding resources has been an issue.
The work around was to embed byte arrays of images and use as a binary resource.
This fix allows embedding resources of jpeg,gif,and many bitmap types.
- Associated with nanoframework/nf-Visual-Studio-extension#729
Created a C# example that displays the bitmaps.
Paint.net was used to import a 32 bit colour image and save in various qualities.
JPEG - 2K bytes.
JPEG - 9K bytes.
JPEF - 12KB bytes ( best for this image size)
GIF - 9KB, dither =8.
GIF - 9KB, dither = 0.
NOTE: Bitmaps are read and then …
=> Fix parsing of bitmap resources

MetadataProcessor.Shared/nanoSkeletonGenerator.cs
- The nested field counter now ignores `MarshalByRefObject` base type.
- Mono Cecil was resolving `MarshalByRefObject` to full .NET mscorlib, thus grabbing wrong information about the class, in particular the class fields. This was causing the offset count for nested fields to be bumped when it shouldn't be.
=> Fix processing of fields for classes deriving from MarshalByRefObject

MetadataProcessor.Shared/Tables/nanoTypeSpecificationsTable.cs
- Method was missing the code to create an entry in the table in case it was missing.
- Fixes nanoFramework/Home#1164.
=> Fix processing of TypeSpec

MetadataProcessor.MsBuildTask/MetaDataProcessorTask.cs, MetadataProcessor.Shared/nanoAssemblyBuilder.cs
- Remove trailing dot which is added by VS output.
=> Fix Log output messages

MetadataProcessor.Tests/Core/Utility/DumperTests.cs, MetadataProcessor.Tests/TestNFApp/Program.cs, MetadataProcessor.Tests/TestNFApp/TestEnumInAnotherAssembly.cs, MetadataProcessor.Tests/TestNFApp/TestNFApp.nfproj, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/IAmAClassWithAnEnum.cs, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/TestNFClassLibrary.nfproj
- Dependency crawler now properly finds usage of enums from other assemblies.
- Add edge case to Unit Test test app.
- Update dumper unit test because of new types added.
- Fixes edge case with enums from other assemblies being wrongly stripped out during minimization.
- Running unit tests.
- Succesfully building nanoframework/System.IO.FileSystem#98 which was failing with "Exception minimizing assembly: Can't find entry in type reference table for System.IO.IOException/IOExceptionErrorCode"
=> Add edge case with referencing enums in another assembly

MetadataProcessor.Shared/Tables/nanoStringTable.cs
- Add check for string table size. Now throws exception when overflowing.
- Resolves issue with assemblies containing many strings which causes an overflow of the string ID. Because of the metadata token limits of .NET nanoFramework, the ID is limited to 65535. Before this, there was no check and the ID was overflowing which caused unwanted results.
- Parsing a project with a huge number of strings.
=> Add check for string table size

MetadataProcessor.Tests/Core/Tables/nanoMethodDefinitionTableTests.cs, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, MetadataProcessor.Tests/TestNFApp/Program.cs, MetadataProcessor.Tests/TestNFApp/TestNFApp.nfproj, MetadataProcessor.Tests/TestNFApp/TestingDelegates.cs, MetadataProcessor.Tests/TestObjectHelper.cs
- Add unit tests for the various delegate flags.
=> Add unit tests for delegate flags in methods

MetadataProcessor.Shared/Tables/nanoMethodDefinitionTable.cs, MetadataProcessor.Tests/Core/Tables/nanoMethodDefinitionTableTests.cs, MetadataProcessor.Tests/TestNFApp/TestNFApp.nfproj, MetadataProcessor.Tests/TestNFApp/TestingDestructors.cs, MetadataProcessor.Tests/TestObjectHelper.cs
- Add check for Finalizer method and set flag accordingly.
- Add Unit tests.
- Addresses nanoFramework/Home#1354.
=> Method flags now processes finalizer

MetadataProcessor.Shared/Extensions/TypeReferenceExtensions.cs, MetadataProcessor.Tests/Core/Tables/nanoAttributesTableTests.cs, MetadataProcessor.Tests/TestNFApp/ClassWithNullAttribs.cs, MetadataProcessor.Tests/TestNFApp/Program.cs, MetadataProcessor.Tests/TestNFApp/TestNFApp.nfproj, MetadataProcessor.Tests/TestObjectHelper.cs
- Add new list of namespaces to exclude from metadata.
- `TypeReferenceExtensions.IsToInclude` extension now uses that list along with the classes to exclude.
- Add new class to test app with DoesNotReturn attribute.
- Improve GetTestNFAppAssemblyDefinitionWithLoadHints.
- Add new test for System.Diagnostics.CodeAnalysis attributes.
- Following the addition of several nullable attributes to mscorlib with nanoframework/CoreLibrary/pull/219, and the subsequent release, it was found that decorating a method with the `DoesNotReturn` attribute on an assembly referencing it would cause a type reference missing exception when running the app.
First finding was that the type was excluded from the metadata (on purpose) by adding a `NFMDP_PE_ExcludeClassByName` entry in the project file. Which was …
=> Improve processing of custom attributes

MetadataProcessor.Shared/Tables/nanoTypeDefinitionTable.cs
- Add check for methods count and throwing exception on failure.
- Add parameter with type full name to compose a meaningfully exception message.
- Currently there is no check if these counters overflow the capacity of the metadata storage. This simplistic approach was taken in the (reasonable) assumption that a type wouldn't have more than 255 methods. If this is exceeded (the counter type allows it) the count is truncated producing errors at type resolution stage.
- This was found when running the Iot.Device.Bq2579x sample on a real device. This is the output at device boot:
The method count for the Bq2579x class is truncated, therefore the type resolution algorithm never finds it.
- Processing the Iot.Device.Bq2579x library. Now an exception is thrown.
=> Add sanity check for methods counters

MetadataProcessor.Tests/Core/ClrIntegrationTests.cs, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, MetadataProcessor.Tests/TestObjectHelper.cs
- Migrate usage of WIN32 virtual device to nanoCLR .NET tool.
- Update CLR integration unit tests to use nanoCLR virtual device.
- Remove dependency of WIN32 nanoCLR in unit test project.
- Need to have these tests back.
- Need to migrate from WIN32 CLR to the new nanoCLR to be able to remove it from the nf-interpreter repo.
- Running all unit tests.
=> Add back CLR integrations tests

MetadataProcessor.Shared/Tables/nanoSignaturesTable.cs, MetadataProcessor.Shared/Tables/nanoTypeDefinitionTable.cs, MetadataProcessor.Tests/Core/Tables/nanoSignaturesTableTests.cs, MetadataProcessor.Tests/MetadataProcessor.Tests.csproj, MetadataProcessor.Tests/TestObjectHelper.cs
- Add new table with built-in types matching the ones used in nf-interpreter.
- Add new helper method WriteDataTypeForTypeDef.
- Replace call in TyepDef.WriteSingleItem to use new helper method.
- Rename primitive type list to comply with code style.
- Add unit tests for new helper method and type list.
- Add new property with mscorlib path.
- Fixes wrong implementation of TypeDef metadata which wasn't using the built-in types correctly (this was overlooked when porting the code from the original C++ tool from .NETMF).
- Adding new unit tests.
- Generated metadata cross checked with old C++ MDP version.
=> Fix generated metadata in TypeDef processing

MetadataProcessor.Tests/Core/ClrIntegrationTests.cs
- Now using the correct header for an HTTP request.
=> Fix usage of HTTP header in nanoCLR install

MetadataProcessor.Console/Program.cs, MetadataProcessor.MsBuildTask/MetaDataProcessorTask.cs, MetadataProcessor.Shared/Tables/nanoTablesContext.cs, MetadataProcessor.Shared/nanoDumperGenerator.cs, MetadataProcessor.Shared/nanoSkeletonGenerator.cs, MetadataProcessor.Tests/Core/ClrIntegrationTests.cs, MetadataProcessor.Tests/Core/Extensions/TypeDefinitionExtensionsTests.cs, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/IAmATypeToExclude.cs, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/IAmAlsoATypeToExclude.cs, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/IAmAnEnumToExclude.cs, MetadataProcessor.Tests/TestNFClassLibrary/TestNFClassLibrary/TestNFClassLibrary.nfproj, MetadataProcessor.Tests/TestObjectHelper.cs
- nanoTablesContext constructor now creates a default list of types to ignore.
- nanoTablesContext constructor now processes type to exclude by checking the custom attributes looking for ExcludeTypeAttribute.
- Dumper generator now checks for attributes to ignore.
- Skeleton generator now checks for attributes to ignore when generating class declarations.
- Uncomment several attribute types that are to be ignored by MDP.
- Minor code style improvements.
- Add test classes with the ExcludeType attributes to NF class test library.
- Add unit tests to cover all these changes.
- Add obsolete attribute to ExcludeClassByName.
- Add warning to MDP console.
- Use new attribute ExcludeTypeAttribute.
- Simplify nfproj file by removing the list of types to exclude.
- Stop adding unused/unnecessary …
=> Add processing of exclude type attribute

MetadataProcessor.Shared/nanoSkeletonGenerator.cs, MetadataProcessor.Tests/Core/StubsGenerationTests.cs
- Extract type comparison to a method.
- Replaced all type comparisons to use this method.
- Add code to help debugging lookup generation.
- Add unit tests to check that types meant to be included are, and only those.
=> Improve type comparison for declarations and stubs

MetadataProcessor.Shared/Tables/nanoSignaturesTable.cs
Improved the efficiency of the code.
[Because it takes too long](https://discord.com/channels/478725473862549535/1377994975811338351).
The generation of the .pe via MSBuild took about 5 minutes for one of my projects. The code in this PR takes about 2 seconds.
Couldn't get the the unit tests to work.
Used a console app (not included) to run the MSBuild task. Used the same arguments as MSBuild to create the *.pe for the project. The resulting *.pe file was (binary) identical to the one produced with the 5-minute version of the build task.
I've copied the new fast build task to the c:\programs... location and am using it now for all NF projects. They all can be run on real hardware.
=> Improve signature generation algorithm
